import type { MediaItem } from '../types';

/**
 * Основной массив медиаматериалов (фотогалерея) — единая точка истинности.
 * Фотографии взяты из реальных материалов сёл и деревень Усинского района.
 */
export const defaultMedia: MediaItem[] = [
	// ── Мутный Материк ──────────────────────────────────────────────
	{
		id: 1,
		title: 'Театральная студия «Бенефис»',
		type: 'photo',
		url: '/settlements/mutny-materik/benefis.jpg',
		category: 'Люди',
		description: 'Театральная студия «Бенефис», с. Мутный Материк',
		date: '2026-05-20',
		uploadedBy: 'editor',
	},
	{
		id: 2,
		title: 'Театральная студия «Бенефис» — репетиция',
		type: 'photo',
		url: '/settlements/mutny-materik/benefis-2.jpg',
		category: 'Люди',
		description: 'Репетиция театральной студии «Бенефис», март 2026',
		date: '2026-03-08',
		uploadedBy: 'editor',
	},
	{
		id: 3,
		title: 'Вокальная студия «Гармония»',
		type: 'photo',
		url: '/settlements/mutny-materik/garmoniya.jpg',
		category: 'Люди',
		description: 'Взрослая вокальная студия «Гармония», с. Мутный Материк',
		date: '2026-05-15',
		uploadedBy: 'editor',
	},
	{
		id: 4,
		title: 'Ансамбль «Йоктысьяс»',
		type: 'photo',
		url: '/settlements/mutny-materik/joktysyas.jpg',
		category: 'Люди',
		description:
			'Танцевальный ансамбль «Йоктысьяс» («Танцующие»), с. Мутный Материк',
		date: '2026-05-12',
		uploadedBy: 'editor',
	},
	{
		id: 5,
		title: 'Танцевальная группа «Ритм»',
		type: 'photo',
		url: '/settlements/mutny-materik/ritm.jpg',
		category: 'Люди',
		description: 'Танцевальная группа «Ритм», с. Мутный Материк',
		date: '2026-05-08',
		uploadedBy: 'admin',
	},
	{
		id: 6,
		title: 'Танцевальная группа «Вдохновение»',
		type: 'photo',
		url: '/settlements/mutny-materik/vdohnovenie.jpg',
		category: 'Люди',
		description: 'Танцевальная группа «Вдохновение», с. Мутный Материк',
		date: '2026-05-05',
		uploadedBy: 'editor',
	},
	{
		id: 7,
		title: 'Ансамбль «Семондрейса кодзувьяс»',
		type: 'photo',
		url: '/settlements/mutny-materik/semondrejsa.jpg',
		category: 'Люди',
		description:
			'Танцевальная группа «Семондрейса кодзувьяс» («Семицветные цветы»), с. Мутный Материк',
		date: '2026-04-28',
		uploadedBy: 'editor',
	},
	{
		id: 8,
		title: 'История с. Мутный Материк — архив',
		type: 'photo',
		url: '/settlements/mutny-materik/history-1.jpg',
		category: 'Архитектура',
		description: 'Архивный снимок из истории с. Мутный Материк',
		date: '2026-03-10',
		uploadedBy: 'admin',
	},
	{
		id: 9,
		title: 'История с. Мутный Материк — архив 2',
		type: 'photo',
		url: '/settlements/mutny-materik/history-2.jpg',
		category: 'Архитектура',
		description: 'Архивный снимок из истории с. Мутный Материк',
		date: '2026-03-10',
		uploadedBy: 'admin',
	},
	// ── Новикбож ────────────────────────────────────────────────────
	{
		id: 10,
		title: 'Театр моды «Бабушкин сундук»',
		type: 'photo',
		url: '/settlements/novikbozh/babushkin-sunduk-1.jpg',
		category: 'Люди',
		description: 'Театр моды «Бабушкин сундук», д. Новикбож',
		date: '2026-04-22',
		uploadedBy: 'admin',
	},
	{
		id: 11,
		title: 'Театр моды «Бабушкин сундук» — гастроли в Санкт-Петербурге',
		type: 'photo',
		url: '/settlements/novikbozh/babushkin-sunduk-2.jpg',
		category: 'События',
		description:
			'Театр моды «Бабушкин сундук» на гастролях в Санкт-Петербурге, 2013',
		date: '2013-06-01',
		uploadedBy: 'admin',
	},
	{
		id: 12,
		title: 'Деревня Новикбож',
		type: 'photo',
		url: '/settlements/novikbozh/village.png',
		category: 'Архитектура',
		description: 'Вид деревни Новикбож',
		date: '2026-01-01',
		uploadedBy: 'admin',
	},
	// ── Колва ───────────────────────────────────────────────────────
	{
		id: 13,
		title: 'С. Колва с реки',
		type: 'photo',
		url: '/settlements/kolva/kolva-village.jpg',
		category: 'Архитектура',
		description: 'Вид на с. Колва с реки',
		date: '2026-01-01',
		uploadedBy: 'admin',
	},
	{
		id: 14,
		title: 'Церковь в с. Колва',
		type: 'photo',
		url: '/settlements/kolva/church.jpg',
		category: 'Архитектура',
		description: 'Церковь в с. Колва',
		date: '2026-01-01',
		uploadedBy: 'admin',
	},
	{
		id: 15,
		title: 'Дом культуры с. Колва',
		type: 'photo',
		url: '/settlements/kolva/dom-kultury.jpg',
		category: 'Архитектура',
		description: 'Здание Дома культуры в с. Колва',
		date: '2026-01-01',
		uploadedBy: 'admin',
	},
	{
		id: 16,
		title: 'Школа-сад с. Колва',
		type: 'photo',
		url: '/settlements/kolva/school.jpg',
		category: 'Архитектура',
		description: 'Здание школы-сада в с. Колва',
		date: '2026-01-01',
		uploadedBy: 'admin',
	},
	{
		id: 17,
		title: 'ФК «Пелысь» — 2025',
		type: 'photo',
		url: '/settlements/kolva/pelys-2025.jpg',
		category: 'События',
		description: 'Футбольный клуб «Пелысь», с. Колва, 2025 год',
		date: '2025-09-01',
		uploadedBy: 'editor',
	},
	{
		id: 18,
		title: 'ФК «Пелысь» — 1984 (основание)',
		type: 'photo',
		url: '/settlements/kolva/pelys-1984.png',
		category: 'События',
		description: 'ФК «Пелысь», год основания — 1984',
		date: '1984-01-01',
		uploadedBy: 'admin',
	},
	{
		id: 19,
		title: 'Спортивная площадка с. Колва',
		type: 'photo',
		url: '/settlements/kolva/sports-1.jpg',
		category: 'События',
		description: 'Новая спортивная площадка в с. Колва',
		date: '2026-04-10',
		uploadedBy: 'editor',
	},
	// ── Усть-Уса ────────────────────────────────────────────────────
	{
		id: 20,
		title: 'Троица в Усть-Усе',
		type: 'photo',
		url: '/settlements/ust-usa/troica-1.jpg',
		category: 'Праздники',
		description: 'Праздник Святой Троицы в с. Усть-Уса',
		date: '2026-04-05',
		uploadedBy: 'editor',
	},
	{
		id: 21,
		title: 'Троица в Усть-Усе — народные гуляния',
		type: 'photo',
		url: '/settlements/ust-usa/troica-2.jpg',
		category: 'Праздники',
		description: 'Народные гуляния на Троицу в с. Усть-Уса',
		date: '2026-04-05',
		uploadedBy: 'editor',
	},
	{
		id: 22,
		title: 'Троица в Усть-Усе — праздничный стол',
		type: 'photo',
		url: '/settlements/ust-usa/troica-3.jpg',
		category: 'Праздники',
		description: 'Праздничное застолье на Троицу в с. Усть-Уса',
		date: '2026-04-05',
		uploadedBy: 'editor',
	},
	// ── Зарни сюр ───────────────────────────────────────────────────
	{
		id: 23,
		title: 'Фестиваль «Зарни сюр»',
		type: 'photo',
		url: '/settlements/zarni-sur/zarni-sur-1.jpg',
		category: 'Праздники',
		description: 'Фестиваль «Зарни сюр» («Золотой рог»)',
		date: '2026-03-28',
		uploadedBy: 'admin',
	},
	{
		id: 24,
		title: 'Фестиваль «Зарни сюр» — выступление',
		type: 'photo',
		url: '/settlements/zarni-sur/zarni-sur-2.jpg',
		category: 'Праздники',
		description: 'Выступление участников фестиваля «Зарни сюр»',
		date: '2026-03-28',
		uploadedBy: 'admin',
	},
	{
		id: 25,
		title: 'Фестиваль «Зарни сюр» — ансамбль',
		type: 'photo',
		url: '/settlements/zarni-sur/zarni-sur-3.jpg',
		category: 'Праздники',
		description: 'Ансамбль на фестивале «Зарни сюр»',
		date: '2026-03-28',
		uploadedBy: 'admin',
	},
	// ── Денисовка ───────────────────────────────────────────────────
	{
		id: 26,
		title: 'Деревня Денисовка — история',
		type: 'photo',
		url: '/settlements/denisovka/history-1.jpg',
		category: 'Архитектура',
		description: 'Исторические снимки деревни Денисовка, май 2026',
		date: '2026-05-20',
		uploadedBy: 'admin',
	},
	{
		id: 27,
		title: 'Деревня Денисовка — фотографии',
		type: 'photo',
		url: '/settlements/denisovka/photo-1.jpg',
		category: 'Архитектура',
		description: 'Фотографии деревни Денисовка',
		date: '2026-05-20',
		uploadedBy: 'admin',
	},
	{
		id: 28,
		title: 'Деревня Денисовка — пейзаж',
		type: 'photo',
		url: '/settlements/denisovka/photo-2.jpg',
		category: 'Природа',
		description: 'Пейзаж деревни Денисовка',
		date: '2026-05-20',
		uploadedBy: 'admin',
	},
	// ── Усть-Лыжа ───────────────────────────────────────────────────
	{
		id: 29,
		title: 'С. Усть-Лыжа',
		type: 'photo',
		url: '/settlements/ust-lyzha/ust-lyzha.jpg',
		category: 'Архитектура',
		description: 'Фотография с. Усть-Лыжа (фото Н. Машковой)',
		date: '2026-03-20',
		uploadedBy: 'editor',
	},
];
